import type { WorkbenchTheme } from "./types";

/**
 * Dark+ (default dark) — pixel-faithful to VSCode's default dark theme.
 * CSS values mirror the original :root block exactly.
 */
export const DARK_PLUS: WorkbenchTheme = {
  id: "dark-plus",
  label: "Dark+ (default dark)",
  kind: "dark",
  css: {
    "--bg-editor": "#1e1e1e",
    "--bg-side": "#252526",
    "--bg-activity": "#333333",
    "--bg-title": "#3c3c3c",
    "--bg-tab": "#2d2d2d",
    "--bg-tab-active": "#1e1e1e",
    "--bg-panel": "#1e1e1e",
    "--bg-input": "#3c3c3c",
    "--bg-dropdown": "#454545",
    "--bg-hover": "#2a2d2e",
    "--bg-list-active": "#37373d",
    "--bg-widget": "#252526",
    "--bg-button": "#0e639c",
    "--bg-button-hover": "#1177bb",
    "--bg-button-secondary": "#3a3d41",
    "--bg-button-secondary-hover": "#45494e",
    "--status-bg": "#007acc",
    "--status-fg": "#ffffff",
    "--border": "#2b2b2b",
    "--border-strong": "#454545",
    "--text": "#cccccc",
    "--text-strong": "#e7e7e7",
    "--text-muted": "#a0a0a0",
    "--text-dim": "#868686",
    "--accent": "#007fd4",
    "--focus": "#007fd4",
    "--list-focus": "#062f4a",
    "--badge-bg": "#4d4d4d",
    "--logo": "#29b6f6",
    "--list-active-fg": "#ffffff",
    "--button-secondary-fg": "#ffffff",
    "--ext-icon": "#75beff",
    "--hex-offset": "#c586c0",
    "--hex-hex": "#9cdcfe",
    "--hex-ascii": "#ce9178",
    "--kbd-bg": "#8080802b",
    "--error": "#f14c4c",
    "--warning": "#cca700",
    "--link": "#3794ff",
    "--scrollbar": "rgba(121, 121, 121, 0.4)",
    "--scrollbar-hover": "rgba(100, 100, 100, 0.7)",
    "--git-modified": "#e2c08d",
    "--git-added": "#81b88b",
    "--git-deleted": "#c74e39",
    "--git-untracked": "#73c991",
    "--git-renamed": "#a09a7f",
  },
  monaco: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "d4d4d4" },
      { token: "comment", foreground: "6a9955", fontStyle: "italic" },
      { token: "keyword", foreground: "569cd6" },
      { token: "keyword.flow", foreground: "c586c0" },
      { token: "number", foreground: "b5cea8" },
      { token: "number.hex", foreground: "b5cea8" },
      { token: "string", foreground: "ce9178" },
      { token: "string.escape", foreground: "d7ba7d" },
      { token: "regexp", foreground: "d16969" },
      { token: "type", foreground: "4ec9b0" },
      { token: "type.identifier", foreground: "4ec9b0" },
      { token: "identifier", foreground: "9cdcfe" },
      { token: "function", foreground: "dcdcaa" },
      { token: "delimiter", foreground: "d4d4d4" },
      { token: "delimiter.bracket", foreground: "ffd700" },
      { token: "operator", foreground: "d4d4d4" },
      { token: "tag", foreground: "569cd6" },
      { token: "metatag", foreground: "569cd6" },
      { token: "attribute.name", foreground: "9cdcfe" },
      { token: "attribute.value", foreground: "ce9178" },
      { token: "variable", foreground: "9cdcfe" },
      { token: "variable.predefined", foreground: "4fc1ff" },
      { token: "constant", foreground: "4fc1ff" },
      { token: "namespace", foreground: "c586c0" },
      { token: "predefined", foreground: "4ec9b0" },
      { token: "annotation", foreground: "dcdcaa" },
    ],
    colors: {
      "editor.background": "#1e1e1e",
      "editor.foreground": "#d4d4d4",
      "editorLineNumber.foreground": "#858585",
      "editorLineNumber.activeForeground": "#c6c6c6",
      "editor.selectionBackground": "#264f78",
      "editor.inactiveSelectionBackground": "#3a3d41",
      "editor.lineHighlightBackground": "#282828",
      "editorCursor.foreground": "#aeafad",
      "editorIndentGuide.background1": "#404040",
      "editorIndentGuide.activeBackground1": "#707070",
      "editorWhitespace.foreground": "#3b3b3b",
      "editorBracketMatch.border": "#888888",
      "editorBracketMatch.background": "#1e1e1e00",
      "editorWidget.background": "#252526",
      "editorWidget.border": "#454545",
      "editorSuggestWidget.background": "#252526",
      "editorSuggestWidget.border": "#454545",
      "editorSuggestWidget.selectedBackground": "#04395e",
      "editorHoverWidget.background": "#252526",
      "editorHoverWidget.border": "#454545",
      "editorGutter.background": "#1e1e1e",
      "editorError.foreground": "#f14c4c",
      "editorWarning.foreground": "#cca700",
      "minimap.background": "#1e1e1e",
      "scrollbarSlider.background": "#79797966",
      "scrollbarSlider.hoverBackground": "#646464b3",
      "scrollbarSlider.activeBackground": "#bfbfbf66",
      "input.background": "#3c3c3c",
      "input.border": "#3c3c3c",
      "focusBorder": "#007fd4",
    },
  },
  xterm: {
    background: "#1e1e1e",
    foreground: "#cccccc",
    cursor: "#ffffff",
    cursorAccent: "#1e1e1e",
    selectionBackground: "rgba(255,255,255,0.25)",
    black: "#000000",
    red: "#cd3131",
    green: "#0dbc79",
    yellow: "#e5e510",
    blue: "#2472c8",
    magenta: "#bc3fbc",
    cyan: "#11a8cd",
    white: "#e5e5e5",
    brightBlack: "#666666",
    brightRed: "#f14c4c",
    brightGreen: "#23d18b",
    brightYellow: "#f5f543",
    brightBlue: "#3b8eea",
    brightMagenta: "#d670d6",
    brightCyan: "#29b8db",
    brightWhite: "#ffffff",
  },
};
