import * as monaco from "monaco-editor";

/** The real "Dark+" (default dark) palette from VSCode. */
export const DARK_PLUS: monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "d4d4d4" },
    { token: "comment", foreground: "6a9955", fontStyle: "italic" },
    { token: "keyword", foreground: "569cd6" },
    { token: "keyword.flow", foreground: "c586c0" },
    { token: "number", foreground: "b5cea8" },
    { token: "number.hex", foreground: "b5cea8" },
    { token: "string", foreground: "ce9178" },
    { token: "string.escape", foreground: "d7ba7d" },
    { token: "regexp", foreground: "d16969" },
    { token: "type", foreground: "4ec9b0" },
    { token: "type.identifier", foreground: "4ec9b0" },
    { token: "identifier", foreground: "9cdcfe" },
    { token: "function", foreground: "dcdcaa" },
    { token: "delimiter", foreground: "d4d4d4" },
    { token: "delimiter.bracket", foreground: "ffd700" },
    { token: "operator", foreground: "d4d4d4" },
    { token: "tag", foreground: "569cd6" },
    { token: "metatag", foreground: "569cd6" },
    { token: "attribute.name", foreground: "9cdcfe" },
    { token: "attribute.value", foreground: "ce9178" },
    { token: "variable", foreground: "9cdcfe" },
    { token: "variable.predefined", foreground: "4fc1ff" },
    { token: "constant", foreground: "4fc1ff" },
    { token: "namespace", foreground: "c586c0" },
    { token: "predefined", foreground: "4ec9b0" },
    { token: "annotation", foreground: "dcdcaa" },
  ],
  colors: {
    "editor.background": "#1e1e1e",
    "editor.foreground": "#d4d4d4",
    "editorLineNumber.foreground": "#858585",
    "editorLineNumber.activeForeground": "#c6c6c6",
    "editor.selectionBackground": "#264f78",
    "editor.inactiveSelectionBackground": "#3a3d41",
    "editor.lineHighlightBackground": "#282828",
    "editorCursor.foreground": "#aeafad",
    "editorIndentGuide.background1": "#404040",
    "editorIndentGuide.activeBackground1": "#707070",
    "editorWhitespace.foreground": "#3b3b3b",
    "editorBracketMatch.border": "#888888",
    "editorBracketMatch.background": "#1e1e1e00",
    "editorWidget.background": "#252526",
    "editorWidget.border": "#454545",
    "editorSuggestWidget.background": "#252526",
    "editorSuggestWidget.border": "#454545",
    "editorSuggestWidget.selectedBackground": "#04395e",
    "editorHoverWidget.background": "#252526",
    "editorHoverWidget.border": "#454545",
    "editorGutter.background": "#1e1e1e",
    "editorError.foreground": "#f14c4c",
    "editorWarning.foreground": "#cca700",
    "minimap.background": "#1e1e1e",
    "scrollbarSlider.background": "#79797966",
    "scrollbarSlider.hoverBackground": "#646464b3",
    "scrollbarSlider.activeBackground": "#bfbfbf66",
    "input.background": "#3c3c3c",
    "input.border": "#3c3c3c",
    "focusBorder": "#007fd4",
  },
};

/** The "Dark+" terminal palette from VSCode. */
export const XTERM_DARK_PLUS = {
  background: "#1e1e1e",
  foreground: "#cccccc",
  cursor: "#ffffff",
  cursorAccent: "#1e1e1e",
  selectionBackground: "rgba(255,255,255,0.25)",
  black: "#000000",
  red: "#cd3131",
  green: "#0dbc79",
  yellow: "#e5e510",
  blue: "#2472c8",
  magenta: "#bc3fbc",
  cyan: "#11a8cd",
  white: "#e5e5e5",
  brightBlack: "#666666",
  brightRed: "#f14c4c",
  brightGreen: "#23d18b",
  brightYellow: "#f5f543",
  brightBlue: "#3b8eea",
  brightMagenta: "#d670d6",
  brightCyan: "#29b8db",
  brightWhite: "#ffffff",
};

monaco.editor.defineTheme("dark-plus", DARK_PLUS);
