import type { WorkbenchTheme } from "./types";

/**
 * Light+ (default light) — mirrors VSCode's default light theme.
 * The activity bar intentionally stays dark (#2c2c2c), exactly like VSCode.
 */
export const LIGHT_PLUS: WorkbenchTheme = {
  id: "light-plus",
  label: "Light+ (default light)",
  kind: "light",
  css: {
    "--bg-editor": "#ffffff",
    "--bg-side": "#f3f3f3",
    "--bg-activity": "#2c2c2c",
    "--bg-title": "#dddddd",
    "--bg-tab": "#ececec",
    "--bg-tab-active": "#ffffff",
    "--bg-panel": "#ffffff",
    "--bg-input": "#ffffff",
    "--bg-dropdown": "#ffffff",
    "--bg-hover": "#e8e8e8",
    "--bg-list-active": "#0060c0",
    "--bg-widget": "#f3f3f3",
    "--bg-button": "#007acc",
    "--bg-button-hover": "#0062a3",
    "--bg-button-secondary": "#e4e4e4",
    "--bg-button-secondary-hover": "#d4d4d4",
    "--status-bg": "#007acc",
    "--status-fg": "#ffffff",
    "--border": "#e5e5e5",
    "--border-strong": "#c8c8c8",
    "--text": "#3b3b3b",
    "--text-strong": "#333333",
    "--text-muted": "#616161",
    "--text-dim": "#717171",
    "--accent": "#0090f1",
    "--focus": "#0090f1",
    "--list-focus": "#e4e6f1",
    "--badge-bg": "#c4c4c4",
    "--logo": "#0066bf",
    "--list-active-fg": "#ffffff",
    "--button-secondary-fg": "#3b3b3b",
    "--ext-icon": "#0098fa",
    "--hex-offset": "#af00db",
    "--hex-hex": "#001080",
    "--hex-ascii": "#a31515",
    "--kbd-bg": "#8080801a",
    "--error": "#e51400",
    "--warning": "#bf8803",
    "--link": "#006ab1",
    "--scrollbar": "rgba(100, 100, 100, 0.4)",
    "--scrollbar-hover": "rgba(100, 100, 100, 0.7)",
    "--git-modified": "#895503",
    "--git-added": "#587c0c",
    "--git-deleted": "#ad0707",
    "--git-untracked": "#388a34",
    "--git-renamed": "#999999",
  },
  monaco: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "000000" },
      { token: "comment", foreground: "008000", fontStyle: "italic" },
      { token: "keyword", foreground: "0000ff" },
      { token: "keyword.flow", foreground: "af00db" },
      { token: "number", foreground: "098658" },
      { token: "number.hex", foreground: "098658" },
      { token: "string", foreground: "a31515" },
      { token: "string.escape", foreground: "ee0000" },
      { token: "regexp", foreground: "811f3f" },
      { token: "type", foreground: "267f99" },
      { token: "type.identifier", foreground: "267f99" },
      { token: "identifier", foreground: "001080" },
      { token: "function", foreground: "795e26" },
      { token: "delimiter", foreground: "000000" },
      { token: "operator", foreground: "000000" },
      { token: "tag", foreground: "800000" },
      { token: "metatag", foreground: "800000" },
      { token: "attribute.name", foreground: "e50000" },
      { token: "attribute.value", foreground: "0451a5" },
      { token: "variable", foreground: "001080" },
      { token: "variable.predefined", foreground: "0070c1" },
      { token: "constant", foreground: "0070c1" },
      { token: "namespace", foreground: "af00db" },
      { token: "predefined", foreground: "267f99" },
      { token: "annotation", foreground: "795e26" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#000000",
      "editorLineNumber.foreground": "#237893",
      "editorLineNumber.activeForeground": "#0b216f",
      "editor.selectionBackground": "#add6ff",
      "editor.inactiveSelectionBackground": "#e5ebf1",
      "editor.lineHighlightBackground": "#0000000a",
      "editorCursor.foreground": "#000000",
      "editorIndentGuide.background1": "#d3d3d3",
      "editorIndentGuide.activeBackground1": "#939393",
      "editorWhitespace.foreground": "#d3d3d3",
      "editorBracketMatch.border": "#007accb0",
      "editorBracketMatch.background": "#00000000",
      "editorWidget.background": "#f3f3f3",
      "editorWidget.border": "#c8c8c8",
      "editorSuggestWidget.background": "#f3f3f3",
      "editorSuggestWidget.border": "#c8c8c8",
      "editorSuggestWidget.selectedBackground": "#0060c0",
      "editorHoverWidget.background": "#f3f3f3",
      "editorHoverWidget.border": "#c8c8c8",
      "editorGutter.background": "#ffffff",
      "editorError.foreground": "#e51400",
      "editorWarning.foreground": "#bf8803",
      "minimap.background": "#ffffff",
      "scrollbarSlider.background": "#64646433",
      "scrollbarSlider.hoverBackground": "#64646459",
      "scrollbarSlider.activeBackground": "#00000026",
      "input.background": "#ffffff",
      "input.border": "#cecece",
      "focusBorder": "#0090f1",
    },
  },
  xterm: {
    background: "#ffffff",
    foreground: "#3b3b3b",
    cursor: "#000000",
    cursorAccent: "#ffffff",
    selectionBackground: "rgba(0,0,0,0.25)",
    black: "#000000",
    red: "#cd3131",
    green: "#00bc00",
    yellow: "#949800",
    blue: "#0451a5",
    magenta: "#bc05bc",
    cyan: "#0598bc",
    white: "#555555",
    brightBlack: "#666666",
    brightRed: "#cd3131",
    brightGreen: "#14ce14",
    brightYellow: "#b5ba00",
    brightBlue: "#0451a5",
    brightMagenta: "#bc05bc",
    brightCyan: "#0598bc",
    brightWhite: "#a5a5a5",
  },
};
