import type { WorkbenchTheme } from "./types";

/** Monokai — the classic dark theme, adapted to the workbench variables. */
export const MONOKAI: WorkbenchTheme = {
  id: "monokai",
  label: "Monokai",
  kind: "dark",
  css: {
    "--bg-editor": "#272822",
    "--bg-side": "#21221d",
    "--bg-activity": "#1e1f1c",
    "--bg-title": "#2d2e27",
    "--bg-tab": "#34352f",
    "--bg-tab-active": "#272822",
    "--bg-panel": "#272822",
    "--bg-input": "#3e3d32",
    "--bg-dropdown": "#3e3d32",
    "--bg-hover": "#414339",
    "--bg-list-active": "#75715e",
    "--bg-widget": "#1e1f1c",
    "--bg-button": "#75715e",
    "--bg-button-hover": "#8b8271",
    "--bg-button-secondary": "#414339",
    "--bg-button-secondary-hover": "#4f5142",
    "--status-bg": "#75715e",
    "--status-fg": "#f8f8f2",
    "--border": "#34352f",
    "--border-strong": "#4f5142",
    "--text": "#f8f8f2",
    "--text-strong": "#ffffff",
    "--text-muted": "#cfcfc2",
    "--text-dim": "#a6a693",
    "--accent": "#a6e22e",
    "--focus": "#e6db74",
    "--list-focus": "#414339",
    "--badge-bg": "#4f5142",
    "--logo": "#a6e22e",
    "--list-active-fg": "#ffffff",
    "--button-secondary-fg": "#f8f8f2",
    "--ext-icon": "#a6e22e",
    "--hex-offset": "#f92672",
    "--hex-hex": "#ae81ff",
    "--hex-ascii": "#e6db74",
    "--kbd-bg": "#80808033",
    "--error": "#f92672",
    "--warning": "#e6db74",
    "--link": "#a6e22e",
    "--scrollbar": "rgba(121, 121, 121, 0.4)",
    "--scrollbar-hover": "rgba(100, 100, 100, 0.7)",
    "--git-modified": "#e2c08d",
    "--git-added": "#a6e22e",
    "--git-deleted": "#f92672",
    "--git-untracked": "#a6e22e",
    "--git-renamed": "#e6db74",
  },
  monaco: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "f8f8f2" },
      { token: "comment", foreground: "75715e", fontStyle: "italic" },
      { token: "keyword", foreground: "f92672" },
      { token: "keyword.flow", foreground: "f92672" },
      { token: "number", foreground: "ae81ff" },
      { token: "number.hex", foreground: "ae81ff" },
      { token: "string", foreground: "e6db74" },
      { token: "string.escape", foreground: "ae81ff" },
      { token: "regexp", foreground: "fd971f" },
      { token: "type", foreground: "66d9ef", fontStyle: "italic" },
      { token: "type.identifier", foreground: "a6e22e", fontStyle: "italic" },
      { token: "identifier", foreground: "f8f8f2" },
      { token: "function", foreground: "a6e22e" },
      { token: "delimiter", foreground: "f8f8f2" },
      { token: "delimiter.bracket", foreground: "f8f8f2" },
      { token: "operator", foreground: "f92672" },
      { token: "tag", foreground: "f92672" },
      { token: "metatag", foreground: "f92672" },
      { token: "attribute.name", foreground: "a6e22e" },
      { token: "attribute.value", foreground: "e6db74" },
      { token: "variable", foreground: "f8f8f2" },
      { token: "variable.predefined", foreground: "ae81ff" },
      { token: "constant", foreground: "ae81ff" },
      { token: "namespace", foreground: "a6e22e" },
      { token: "predefined", foreground: "66d9ef" },
      { token: "annotation", foreground: "a6e22e" },
    ],
    colors: {
      "editor.background": "#272822",
      "editor.foreground": "#f8f8f2",
      "editorLineNumber.foreground": "#90908a",
      "editorLineNumber.activeForeground": "#c2c2bf",
      "editor.selectionBackground": "#49483e",
      "editor.inactiveSelectionBackground": "#414339",
      "editor.lineHighlightBackground": "#3e3d32",
      "editorCursor.foreground": "#f8f8f0",
      "editorIndentGuide.background1": "#464741",
      "editorIndentGuide.activeBackground1": "#75715e",
      "editorWhitespace.foreground": "#464741",
      "editorBracketMatch.border": "#75715e",
      "editorBracketMatch.background": "#27282200",
      "editorWidget.background": "#1e1f1c",
      "editorWidget.border": "#75715e",
      "editorSuggestWidget.background": "#1e1f1c",
      "editorSuggestWidget.border": "#75715e",
      "editorSuggestWidget.selectedBackground": "#75715e",
      "editorHoverWidget.background": "#1e1f1c",
      "editorHoverWidget.border": "#75715e",
      "editorGutter.background": "#272822",
      "editorError.foreground": "#f92672",
      "editorWarning.foreground": "#e6db74",
      "minimap.background": "#272822",
      "scrollbarSlider.background": "#75715e66",
      "scrollbarSlider.hoverBackground": "#75715e99",
      "scrollbarSlider.activeBackground": "#75715eb3",
      "input.background": "#3e3d32",
      "input.border": "#3e3d32",
      "focusBorder": "#a6e22e",
    },
  },
  xterm: {
    background: "#272822",
    foreground: "#f8f8f2",
    cursor: "#f8f8f0",
    cursorAccent: "#272822",
    selectionBackground: "rgba(255,255,255,0.25)",
    black: "#272822",
    red: "#f92672",
    green: "#a6e22e",
    yellow: "#e6db74",
    blue: "#ae81ff",
    magenta: "#fd971f",
    cyan: "#66d9ef",
    white: "#f8f8f2",
    brightBlack: "#75715e",
    brightRed: "#f92672",
    brightGreen: "#a6e22e",
    brightYellow: "#e6db74",
    brightBlue: "#ae81ff",
    brightMagenta: "#fd971f",
    brightCyan: "#66d9ef",
    brightWhite: "#ffffff",
  },
};
